### PR TITLE
Json Standard Output Generation for Notebooks

### PR DESCRIPTION
**Pull request by JonhasSC**
This PR is focused on answering https://github.com/lanl-ansi/qc-applications/issues/11, i.e, for some experiment, we port the logical resource estimates into a json file. We generate a json file for each subcircuit and for the global circuit as well. An example of a generated RE is the following:
```json
{
    "circuit_depth": 5034,
    "circuit_name": "Trotter/triangle_circuits/trotter_triangle",
    "clifford_count": 1193230,
    "gate_count": 1986928,
    "max_t_count_single_wire": 17365713600,
    "num_qubits": 1024,
    "t_count": 793698,
    "t_depth": 4932,
    "t_depth_wire": 800,
    "total_t_depth": 107059624344,
    "trotter_steps_required": 21707142
}
```

The idea is that the user can either keep this logical resource estimate as a dict and work with it, or consume the json to then work with it.

### CODE REVIEW

**Comment by zmorrell** [comment]
One field that I would likely want to see would be a list of subcircuits/sub-estimates.  For example with QSP, we would have a sub-resource for all of the various block encoding operations, while for Trotter, it would not have any sub-estimates.  We would also want to have a field for number of circuit occurrences and perhaps total depth vs single instance depth, etc.

**Comment by JonhasSC** [comment]
Given the feedback, we see the following re generated for a trotter approximation:
```json
{
    "num_qubits": 100,
    "t_count": 56306,
    "t_depth": 3104,
    "max_t_depth_wire": 604,
    "gate_count": 143786,
    "clifford_count": 87480,
    "circuit_depth": 3116,
    "total_t_depth": 16657814656,
    "max_t_count_single_wire": 3241404656,
    "trotter_steps_required": 5366564
}
```
and for a qsp estimation, we'd get:
```json
{
    "num_qubits": 119,
    "gate_count": 39419156000.0,
    "circuit_depth": 37438116000.0,
    "t_count": 15439782000.0,
    "t_depth": 15191935000.0,
    "t_depth_wire": 4081670000.0,
    "clifford_count": 23979374000.0,
    "subcircuit_info": [
        {
            "QSP/square_circuits/_PauliX": {
                "num_qubits": 1,
                "t_count": 0,
                "t_depth": 0,
                "max_t_depth_wire": 0,
                "gate_count": 1,
                "clifford_count": 1,
                "circuit_depth": 1,
                "circuit occurrences": 18000
            }
        },
        {
            "QSP/square_circuits/Rx": {
                "num_qubits": 1,
                "t_count": 102,
                "t_depth": 102,
                "max_t_depth_wire": 102,
                "gate_count": 261,
                "clifford_count": 159,
                "circuit_depth": 261,
                "circuit occurrences": 2000
            }
        },
        {
            "QSP/square_circuits/UnitaryBlockEncode": {
                "num_qubits": 119,
                "t_count": 24270,
                "t_depth": 24076,
                "max_t_depth_wire": 6602,
                "gate_count": 61813,
                "clifford_count": 37543,
                "circuit_depth": 60527,
                "circuit occurrences": 292000
            }
        },
        {
            "QSP/square_circuits/Ry": {
                "num_qubits": 1,
                "t_count": 96,
                "t_depth": 96,
                "max_t_depth_wire": 96,
                "gate_count": 245,
                "clifford_count": 149,
                "circuit_depth": 245,
                "circuit occurrences": 292000
            }
        },
        {
            "QSP/square_circuits/_InverseCompositeGate": {
                "num_qubits": 119,
                "t_count": 28296,
                "t_depth": 27702,
                "max_t_depth_wire": 7170,
                "gate_count": 72431,
                "clifford_count": 44135,
                "circuit_depth": 67112,
                "circuit occurrences": 292000
            }
        },
        {
            "QSP/square_circuits/Reflect": {
                "num_qubits": 17,
                "t_count": 214,
                "t_depth": 153,
                "max_t_depth_wire": 110,
                "gate_count": 508,
                "clifford_count": 294,
                "circuit_depth": 328,
                "circuit occurrences": 291000
            }
        }
    ]
}
```

**Comment by JonhasSC** [comment]
Given our discussion this morning, the trotter RE now looks like:
```json
{
    "num_qubits": 2176,
    "t_count": 3251452,
    "t_depth": 9263,
    "max_t_depth_wire": 1816,
    "gate_count": 8319209,
    "clifford_count": 5067757,
    "circuit_depth": 9318,
    "total_t_depth": 1997544052268,
    "max_t_count_single_wire": 391616106976,
    "trotter_steps_required": 215647636,
    "subcircuit_info": {}
}
```

and the qsp RE looks like:
```json
{
    "num_qubits": 2205,
    "gate_count": 501499419441000.0,
    "circuit_depth": 487825621781000.0,
    "t_count": 195007261740000.0,
    "t_depth": 193754401509000.0,
    "t_depth_wire": 92952312314000.0,
    "clifford_count": 306492157701000.0,
    "subcircuit_info": {
        "QSP/RuCl_circuits/_PauliX": {
            "num_qubits": 1,
            "t_count": 0,
            "t_depth": 0,
            "max_t_depth_wire": 0,
            "gate_count": 1,
            "clifford_count": 1,
            "circuit_depth": 1,
            "circuit occurrences": 28000
        },
        "QSP/RuCl_circuits/Rx": {
            "num_qubits": 1,
            "t_count": 102,
            "t_depth": 102,
            "max_t_depth_wire": 102,
            "gate_count": 261,
            "clifford_count": 159,
            "circuit_depth": 261,
            "circuit occurrences": 2000
        },
        "QSP/RuCl_circuits/UnitaryBlockEncode": {
            "num_qubits": 2205,
            "t_count": 1651076,
            "t_depth": 1650579,
            "max_t_depth_wire": 824662,
            "gate_count": 4228250,
            "clifford_count": 2577174,
            "circuit_depth": 4225129,
            "circuit occurrences": 55270000
        },
        "QSP/RuCl_circuits/Ry": {
            "num_qubits": 1,
            "t_count": 96,
            "t_depth": 96,
            "max_t_depth_wire": 96,
            "gate_count": 247,
            "clifford_count": 151,
            "circuit_depth": 247,
            "circuit occurrences": 55270000
        },
        "QSP/RuCl_circuits/_InverseCompositeGate": {
            "num_qubits": 2205,
            "t_count": 1876810,
            "t_depth": 1854768,
            "max_t_depth_wire": 856918,
            "gate_count": 4844462,
            "clifford_count": 2967652,
            "circuit_depth": 4600523,
            "circuit occurrences": 55270000
        },
        "QSP/RuCl_circuits/Reflect": {
            "num_qubits": 27,
            "t_count": 284,
            "t_depth": 155,
            "max_t_depth_wire": 110,
            "gate_count": 669,
            "clifford_count": 385,
            "circuit_depth": 329,
            "circuit occurrences": 55269000
        }
    }
}
```

**Comment by JonhasSC** [comment]
> We shouldn't have a distinct resource estimate for trotterization and QSP. Instead of "Trotter Steps Required" we should just have number of circuit occurrences, as with QSP. Also, in both cases, the number of occurrences should be present, even if the number is just one, since for example with QSP, we may want to modify the field based on the number of repetitions of the circuit we are performing

This has now been responded with by the most recent PR. Trotter_approximation:
```json
{
    "num_qubits": 2176,
    "gate_count": 8911921.0,
    "circuit_depth": 8911921.0,
    "t_count": 3289398.0,
    "t_depth": 3289398.0,
    "max_t_depth_wire": 3289398.0,
    "clifford_count": 5622523.0,
    "circuit_occurences": 215647636,
    "subcircuit_info": {
        "<class 'cirq.ops.common_gates.HPowGate": {
            "num_qubits": 1,
            "t_count": 0,
            "t_depth": 0,
            "max_t_depth_wire": 0,
            "gate_count": 1,
            "clifford_count": 1,
            "circuit_depth": 1,
            "subcicruit_occurrences": 34296
        },
        "<class 'cirq.ops.common_gates.Rz": {
            "num_qubits": 1,
            "t_count": 102,
            "t_depth": 102,
            "max_t_depth_wire": 102,
            "gate_count": 259,
            "clifford_count": 157,
            "circuit_depth": 259,
            "subcicruit_occurrences": 32249
        },
        "<class 'cirq.ops.common_gates.Rx": {
            "num_qubits": 1,
            "t_count": 0,
            "t_depth": 0,
            "max_t_depth_wire": 0,
            "gate_count": 3,
            "clifford_count": 3,
            "circuit_depth": 3,
            "subcicruit_occurrences": 34296
        },
        "<class 'cirq.ops.common_gates.CXPowGate": {
            "num_qubits": 2,
            "t_count": 0,
            "t_depth": 0,
            "max_t_depth_wire": 0,
            "gate_count": 11,
            "clifford_count": 11,
            "circuit_depth": 11,
            "subcicruit_occurrences": 38386
        }
    }
}
```
qsp:
```json
{
    "num_qubits": 2205,
    "gate_count": 501499419441000.0,
    "circuit_depth": 487825621781000.0,
    "t_count": 195007261740000.0,
    "t_depth": 193754401509000.0,
    "max_t_depth_wire": 92952312314000.0,
    "clifford_count": 306492157701000.0,
    "circuit_occurences": 1000,
    "subcircuit_info": {
        "<class 'cirq.ops.pauli_gates._PauliX": {
            "num_qubits": 1,
            "t_count": 0,
            "t_depth": 0,
            "max_t_depth_wire": 0,
            "gate_count": 1,
            "clifford_count": 1,
            "circuit_depth": 1,
            "subcicruit_occurrences": 28000
        },
        "<class 'cirq.ops.common_gates.Rx": {
            "num_qubits": 1,
            "t_count": 102,
            "t_depth": 102,
            "max_t_depth_wire": 102,
            "gate_count": 261,
            "clifford_count": 159,
            "circuit_depth": 261,
            "subcicruit_occurrences": 2000
        },
        "<class 'pyLIQTR.circuits.operators.hamiltonian_encodings.UnitaryBlockEncode": {
            "num_qubits": 2205,
            "t_count": 1651076,
            "t_depth": 1650579,
            "max_t_depth_wire": 824662,
            "gate_count": 4228250,
            "clifford_count": 2577174,
            "circuit_depth": 4225129,
            "subcicruit_occurrences": 55270000
        },
        "<class 'cirq.ops.common_gates.Ry": {
            "num_qubits": 1,
            "t_count": 96,
            "t_depth": 96,
            "max_t_depth_wire": 96,
            "gate_count": 247,
            "clifford_count": 151,
            "circuit_depth": 247,
            "subcicruit_occurrences": 55270000
        },
        "<class 'cirq.ops.raw_types._InverseCompositeGate": {
            "num_qubits": 2205,
            "t_count": 1876810,
            "t_depth": 1854768,
            "max_t_depth_wire": 856918,
            "gate_count": 4844462,
            "clifford_count": 2967652,
            "circuit_depth": 4600523,
            "subcicruit_occurrences": 55270000
        },
        "<class 'pyLIQTR.circuits.operators.reflect.Reflect": {
            "num_qubits": 27,
            "t_count": 284,
            "t_depth": 155,
            "max_t_depth_wire": 110,
            "gate_count": 669,
            "clifford_count": 385,
            "circuit_depth": 329,
            "subcicruit_occurrences": 55269000
        }
    }
}
```

This PR also includes a change to compartmentalizing functions that have been reused across multiple notebooks such as the estimate_trotter and estimate_qsp function call. Also, the plotted_histograms now include the median T width, such as:
image

**Comment by zmorrell** [comment]
LGTM

**Pull request merged**
