### PR TITLE
Bugfix for generating appropritate resource estimates for trotter circuit and for outputting trotter circuits

### PR DESCRIPTION
**Pull request by JonhasSC**
This PR focuses on fixing a bug for outputting the appropriate resource estimates for trotter circuits. This bug was not affecting circuits generated from performing a qsp time evolution, but was affecting trotter circuits. Thus, we will be comparing the similarity between the two.

Consider the json file generated from a square-like ising lattice. With an energy precision of 1e-6, given the use of QSP to simulate the time dynamics of this hamiltonian, we get:
```json
{
    "num_qubits": 119,
    "gate_count": 39419156000.0,
    "circuit_depth": 37438116000.0,
    "t_count": 15439782000.0,
    "t_depth": 15191935000.0,
    "max_t_depth_wire": 4081670000.0,
    "clifford_count": 23979374000.0,
    "circuit_occurences": 1000,
    "subcircuit_info": {
        "<class 'cirq.ops.pauli_gates._PauliX": {
            "num_qubits": 1,
            "gate_count": 1,
            "circuit_depth": 1,
            "t_count": 0,
            "t_depth": 0,
            "max_t_depth_wire": 0,
            "clifford_count": 1,
            "subcicruit_occurrences": 18
        },
        "<class 'cirq.ops.common_gates.Rx": {
            "num_qubits": 1,
            "gate_count": 261,
            "circuit_depth": 261,
            "t_count": 102,
            "t_depth": 102,
            "max_t_depth_wire": 102,
            "clifford_count": 159,
            "subcicruit_occurrences": 2
        },
        "<class 'pyLIQTR.circuits.operators.hamiltonian_encodings.UnitaryBlockEncode": {
            "num_qubits": 119,
            "gate_count": 61813,
            "circuit_depth": 60527,
            "t_count": 24270,
            "t_depth": 24076,
            "max_t_depth_wire": 6602,
            "clifford_count": 37543,
            "subcicruit_occurrences": 292
        },
        "<class 'cirq.ops.common_gates.Ry": {
            "num_qubits": 1,
            "gate_count": 245,
            "circuit_depth": 245,
            "t_count": 96,
            "t_depth": 96,
            "max_t_depth_wire": 96,
            "clifford_count": 149,
            "subcicruit_occurrences": 292
        },
        "<class 'cirq.ops.raw_types._InverseCompositeGate": {
            "num_qubits": 119,
            "gate_count": 72431,
            "circuit_depth": 67112,
            "t_count": 28296,
            "t_depth": 27702,
            "max_t_depth_wire": 7170,
            "clifford_count": 44135,
            "subcicruit_occurrences": 292
        },
        "<class 'pyLIQTR.circuits.operators.reflect.Reflect": {
            "num_qubits": 17,
            "gate_count": 508,
            "circuit_depth": 328,
            "t_count": 214,
            "t_depth": 153,
            "max_t_depth_wire": 110,
            "clifford_count": 294,
            "subcicruit_occurrences": 291
        }
    }
}
```
vs the resource estimates we get from a second order trotter evaluation that gets scaled to account for the number of trotter steps:
```json
{
    "num_qubits": 100,
    "gate_count": 771636771304,
    "circuit_depth": 16722213424,
    "t_count": 302169752584,
    "t_depth": 16657814656,
    "max_t_depth_wire": 3241404656,
    "clifford_count": 469467018720,
    "circuit_occurences": 1,
    "subcircuit_info": {
        "Trotter_Unitary": {
            "num_qubits": 100,
            "gate_count": 143786,
            "clifford_count": 87480,
            "t_count": 56306,
            "t_depth": 3104,
            "max_t_depth_wire": 604,
            "circuit_depth": 3116,
            "subcicruit_occurrences": 5366564
        }
    }
}
```
Not only are these resource estimates more appropriate than whats currently on dev, but we also see all of the appropriate relationships being held. Those are:
1. gate_count = clifford_count + t_count
2. We see the following hold true: max_t_depth_wire <= t_depth <= t_count
3. circuit_occurences =1 for the complete trotter circuit and then subcircuit_occurences will equal to the total number of step that the trotter evaluation was approximated. 

Additionally, this change introduces a fix to the subcircuit_info key to resource estimates generated from trotter circuits. The subcircuit info will only hold one key which is the trotter_unitary subcircuit, and will hold resource estimates for a single trotter step.

This PR also works to respond to https://github.com/lanl-ansi/qc-applications/issues/25  by outputting the qasm for a single trotter step if the user have `write_circuits=True` in the `estimate_trotter` function call. 

The reason we had this issue is due to using openfermion for trotterization. Through openfermion, this will just produce the trotter circuit as a global circuit. In contrast, through pyLIQTR, when using QPE for GSEE, this will output a global circuit with a nested Trotter_Unitary type, which was created by pyLIQTR. As such, to handle this discrepancy, QCA simply outputs the single step trotter circuit to qasm. This involves generating both the Clifford + T circuit and its corresponding algorithmic circuit.

### CODE REVIEW

**Comment by zmorrell** [comment]
On initial look-through this looks good and correct.  I will want to make sure that there will not be any sort of conflicting definitions from this and #30 for the incorporation of the scaling arguments in #30.

**Comment by JonhasSC** [comment]
Given the discussion we had, we are now getting the following output. Consider the following RE generated from performing qsp on a RuCl_row_13 circuit:
```json
{
    "num_qubits": 2205,
    "gate_count": 501499419441000,
    "circuit_depth": 487825621781000,
    "t_count": 195007261740000,
    "t_depth": 193754401509000,
    "max_t_depth_wire": 92952312314000,
    "clifford_count": 306492157701000,
    "circuit_occurences": 1,
    "subcircuit_info": {
        "QSP_Step": {
            "gate_count": 501499419441,
            "circuit_depth": 487825621781,
            "t_count": 195007261740,
            "t_depth": 193754401509,
            "max_t_depth_wire": 92952312314,
            "clifford_count": 306492157701,
            "circuit_occurences": 1000,
            "subcircuit_info": {
                "<class 'cirq.ops.pauli_gates._PauliX": {
                    "num_qubits": 1,
                    "gate_count": 1,
                    "circuit_depth": 1,
                    "t_count": 0,
                    "t_depth": 0,
                    "max_t_depth_wire": 0,
                    "clifford_count": 1,
                    "subcicruit_occurrences": 28
                },
                "<class 'cirq.ops.common_gates.Rx": {
                    "num_qubits": 1,
                    "gate_count": 261,
                    "circuit_depth": 261,
                    "t_count": 102,
                    "t_depth": 102,
                    "max_t_depth_wire": 102,
                    "clifford_count": 159,
                    "subcicruit_occurrences": 2
                },
                "<class 'pyLIQTR.circuits.operators.hamiltonian_encodings.UnitaryBlockEncode": {
                    "num_qubits": 2205,
                    "gate_count": 4228250,
                    "circuit_depth": 4225129,
                    "t_count": 1651076,
                    "t_depth": 1650579,
                    "max_t_depth_wire": 824662,
                    "clifford_count": 2577174,
                    "subcicruit_occurrences": 55270
                },
                "<class 'cirq.ops.common_gates.Ry": {
                    "num_qubits": 1,
                    "gate_count": 247,
                    "circuit_depth": 247,
                    "t_count": 96,
                    "t_depth": 96,
                    "max_t_depth_wire": 96,
                    "clifford_count": 151,
                    "subcicruit_occurrences": 55270
                },
                "<class 'cirq.ops.raw_types._InverseCompositeGate": {
                    "num_qubits": 2205,
                    "gate_count": 4844462,
                    "circuit_depth": 4600523,
                    "t_count": 1876810,
                    "t_depth": 1854768,
                    "max_t_depth_wire": 856918,
                    "clifford_count": 2967652,
                    "subcicruit_occurrences": 55270
                },
                "<class 'pyLIQTR.circuits.operators.reflect.Reflect": {
                    "num_qubits": 27,
                    "gate_count": 669,
                    "circuit_depth": 329,
                    "t_count": 284,
                    "t_depth": 155,
                    "max_t_depth_wire": 110,
                    "clifford_count": 385,
                    "subcicruit_occurrences": 55269
                }
            }
        }
    }
}

```
Where you see the three layers expressed appropriately. 
Similarly, we can have the following when performing trotter:
```json
{
    "num_qubits": 2176,
    "gate_count": 1793764799562896,
    "circuit_depth": 2008973376976,
    "t_count": 701178288454000,
    "t_depth": 1995603223544,
    "max_t_depth_wire": 392047402248,
    "clifford_count": 1092586511108896,
    "circuit_occurences": 1,
    "subcircuit_info": {
        "Trotter_Step": {
            "num_qubits": 2176,
            "gate_count": 8318036,
            "clifford_count": 5066536,
            "t_count": 3251500,
            "t_depth": 9254,
            "max_t_depth_wire": 1818,
            "circuit_depth": 9316,
            "subcicruit_occurrences": 215647636,
            "subcircuit_info": {}
        }
    }
}
```
where we see the three layers as well, but, the last one is empty. We also see all the relationships being held and the standard being kept.

**Comment by JonhasSC** [comment]
Note that this does not take into consideration the scaling factor when performing GSEE. That will be up to the responsibility of either the Quantum Chemistry PR or HTSC  pr to respond to that.

**Comment by zmorrell** [comment]
The QSP resource estimate seems to be missing the number of qubits in the first layer of the subcircuit information

**Comment by zmorrell** [comment]
Lastly, based on our conversation from earlier, evolution time can be a real number/float since we don't want to be constrained to only using integer evolution times

**Comment by zmorrell** [comment]
LGTM!

**Pull request merged**
