### PR TITLE
RuCl migration of pyLIQTR-1.0

### PR DESCRIPTION
**Pull request by zain2864**
Modified RuCl notebook to support pyLIQTR 1.0

### CODE REVIEW

**Comment by JonhasSC** [comment]
Remove unused random, np, openfermion, and pyLIQTR imports

**Comment by JonhasSC** [comment]
In estimate_trotter, if the user wants to write the circuit to qasm, the circuit you're specifying is undefined, please use the appropriate one

**Review by JonhasSC — CHANGES_REQUESTED** [review]
Just respond to the comments and it would be good. Everything else lgtm.

**Comment by zmorrell** [comment]
Is random unused?  I would have thought that we would be using it to seed the rng.  I may be mistaken, but I thought that numpy and python use different random number generators, so it is important to seed both.  If there is not currently a line about rng seeding, it should be added near the top of the notebook since the angles being generated are random and we want replicability.

**Comment by zain2864** [comment]
I have fixed the issues given by Jonhas, added random.seed() for the angles, and I am now going to work to add in support with the QCA package from dev.

**Comment by zain2864** [comment]
I have restructured notebook to use the QCA package, and fixed the header of plot_T_histogram in the qca package, and the notebook is running. If there is anything else, please let me know.

**Comment by JonhasSC** [comment]
in estimate_qsp, outfile_qasm_high_level variable is unused. Remove or use it

**Comment by JonhasSC** [comment]
incorrect usage of plotting the trotterized RuCl row. There is a function in utils that plots your circuit, plot_histogram.

**Comment by JonhasSC** [comment]
Fix plotting for both trotterized and qsp approximations by using the appropriate function call, and constructing the appropriate directories to where to store the data

**Comment by JonhasSC** [comment]
Fix assign_hexagonal_labels to allowing generic x y z labels for hexagonal like hamiltonians. Will need to fix for RuCl and magnetic lattice notebooks.

**Comment by zain2864** [comment]
Removed unused QubitOperator, Graph, and plot_T_histogram imports, removed estimate_qsp, outfile_qasm_high_level variable it is unused, fixed plotting to use plot_histogram and save files in correct directories, undid kwargs change, changed assign_hexagonal_labels to allowing generic x y z labels for hexagonal like hamiltonians and updated rucl and magentic lattice notebooks

**Comment by JonhasSC** [comment]
LGTM besides removing comment for qsp and uppercase kitaev terms

**Comment by zmorrell** [comment]
LGTM.  We can make the plotting work later imo.

**Comment by zmorrell** [comment]
Actually, real quick: should we provide default arguments of 'X', 'Y', and 'Z' for assign_hexagon_labels?  I would think so, but they are missing.  Ultimately, it doesn't matter so long as the notebooks are up to date, but it could reduce typing in the most common case.

**Comment by zain2864** [comment]
I added the default arguments of 'X', 'Y', and 'Z' for assign_hexagon_labels, removed the commented code for plotting for qsp and changed to uppercase labels for RuCl terms

**Pull request merged**
