### PR TITLE
WIP: functionality for new json schema and for complete decomposition

### PR DESCRIPTION
**Pull request by JonhasSC**

### CODE REVIEW

**Comment by zmorrell** [comment]
Is the keyword argument in the EstimateMetaData class supposed to be `implementation` or implementation`?  In the HTSC notebook, it calls with `implementation` and crashes.

**Comment by zmorrell** [comment]
I had some issues with a detached head, so double check that I didn't mess anything up.

**Comment by zmorrell** [comment]
I believe that it should be good to merge now.  We might need to fix the issue with the detached HEAD.

**Comment by JonhasSC** [comment]
Merging given our discussion that a detached HEAD is not an issue

**Pull request merged**
