### PR TITLE
Continuous Integration + Unit Test Suite

### PR DESCRIPTION
**Pull request by JonhasSC**
This PR includes adding three new github actions for improving the development process for QCA. The three github actions include:

1. Pylint for static code analysis
2. Mypy - performs compile time type checking with no overhead with some python VM
3. Test Suite - unit test cases for the util files. In the future, can add regression test cases. 

The idea is that once this PR is merged, there will be an additional check that no branch can be merged to main without passing all test cases. However, the type checkers will be used to show possible improvements that can optionally be implemented. 

This PR aims to solve https://github.com/lanl-ansi/qc-applications/issues/9

### CODE REVIEW

**Comment by zmorrell** [comment]
Being somewhat unfamiliar with Mypy and Pylint in the context of CI, I notice that they seem to be failing due to non-critical issues (Pylint raising issues with code line length, and Mypy raising issues with type inference being taken advantage of).  Is there a way to get these to be raised as warnings rather than errors so that it doesn't look like CI is failing?

In a somewhat different vein, since I believe we claim that we support Python >= 3.9, should we include tests for these (3.9, 3.10, 3.11)?

Otherwise LGTM!

**Comment by JonhasSC** [comment]
> Being somewhat unfamiliar with Mypy and Pylint in the context of CI, I notice that they seem to be failing due to non-critical issues (Pylint raising issues with code line length, and Mypy raising issues with type inference being taken advantage of). Is there a way to get these to be raised as warnings rather than errors so that it doesn't look like CI is failing?
> 
> In a somewhat different vein, since I believe we claim that we support Python >= 3.9, should we include tests for these (3.9, 3.10, 3.11)?
> 
> Otherwise LGTM!

Unfortunately, github only has three states for a github action, pending, passing, or failing state of status checks, which was found here https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/about-status-checks

Since we do support >=python3.9, we can run multiple versions of the test suite with different python versions, it would just increase the runtime.

**Comment by zmorrell** [comment]
Alright.  That is unfortunate, but understandable.  With regards to the Python versioning, upon looking, it appears that it takes ~2.5 minutes for the full build pipeline to run.  Since that is already a reasonably significant amount of time, I think that we can safely merge this and update later if we want to be extra careful.  We could possibly just use Python 3.9 and Python Latest as well.  I think this is good for now though

In summary: LGTM!

**Comment by JonhasSC** [comment]
Will be merging this over to dev after getting approval

**Pull request merged**
