### PR TITLE
QCA - Initial package structure

### PR DESCRIPTION
**Pull request by JonhasSC**
The purpose of this PR isn't to introduce the initial packaged qc-applications deliverable, but rather to begin the structuring of the package. This PR is very bare bones and acts as an entryway to subsequent PRs. It introduces the qca module and a nested utils module with some utility functions. The goal is that for subsequent PRs that are migrating to PyLIQTR 1.0.0 to update both the utils module and their respective notebook. 

Therefore, we should expect the flow of merges to dev be the following:
    1. This PR
    2. Other PRs that are modifying their respective notebook and utils module
    3. Merge to main

The distinction to make here is that once we merge to main, it is only satisfying the first vertical slice of delivering qc-applications, i.e, migrating all notebooks to pyLIQTR1.0.0. The next vertical slice is to actually turn qc-applications into a package and perform a simple example with it. 

note that due to pyLIQTR restrictions, the requirements aren't ideal. Once pyLIQTR makes the appropriate changes, the requirements will be changed to a stable release of cirq.

### CODE REVIEW

**Comment by zmorrell** [comment]
Some comments:
1. In the `.gitignore` file, I suspect we can do `*.bak` rather than just `env.bak`.  This would prevent people from pushing any backup files they may have.
2. In `pyproject.toml`, the `readme.md` should be `README.md` (not sure if this really matters that much tbh).
3. Does it make more sense to change the pyLIQTR requirement to 1.0.0 when the merge of the various notebook updates has not been pulled into dev as far as I know?  We may want to keep this on 0.3 or 0.3.3 while development is still underway, and we can modify to 1.0.0 when the updated notebooks are ready to merge in.

**Comment by JonhasSC** [comment]
> Some comments:
> 
>     1. In the `.gitignore` file, I suspect we can do `*.bak` rather than just `env.bak`.  This would prevent people from pushing any backup files they may have.
> 
>     2. In `pyproject.toml`, the `readme.md` should be `README.md` (not sure if this really matters that much tbh).
> 
>     3. Does it make more sense to change the pyLIQTR requirement to 1.0.0 when the merge of the various notebook updates has not been pulled into dev as far as I know?  We may want to keep this on 0.3 or 0.3.3 while development is still underway, and we can modify to 1.0.0 when the updated notebooks are ready to merge in.

I agree with 1 and 2. Regarding 3, it depends on what your views on a dev branch are. I view dev as ongoing development, that could not be merged to main **until** it gets tagged and then merged to main. So, it is up to the responsibility of the maintainer to assure that their dev branch functions appropriately and is eligible to be merged to main. However, we can also view dev that it is ongoing development, that at any moment's notice, could be merged to main and still function properly. 

Given that, do you think its more appropriate to tag the pyliqtr versioning to be 0.3.3 for now and have it be the responsibility of additional PRs to make those changes accordingly?

**Comment by zmorrell** [comment]
My thought is that dev serves as a staging branch for the next major version release (admittedly, this makes more sense on a package with version releases, which is hopefully a stage we will reach down the line).  In my opinion the dev branch should be an unstable branch that is expected to compile, but may not be main branch ready yet because it may not have been tested to the same degree.  From the dev branch, feature development branches can be made and merged.  After rigorous testing of the main branch prior to a version update, the dev branch can be merged into main and start anew.  That would be my thought on the workflow, but if you have a different idea, I am open to discussing it.

**Comment by JonhasSC** [comment]
> My thought is that dev serves as a staging branch for the next major version release (admittedly, this makes more sense on a package with version releases, which is hopefully a stage we will reach down the line). In my opinion the dev branch should be an unstable branch that is expected to compile, but may not be main branch ready yet because it may not have been tested to the same degree. From the dev branch, feature development branches can be made and merged. After rigorous testing of the main branch prior to a version update, the dev branch can be merged into main and start anew. That would be my thought on the workflow, but if you have a different idea, I am open to discussing it.

I don't have a strong preference to whichever view we have on the dev branch so lets just approach it as a staging branch. I'll go ahead and change the versioning

**Comment by zmorrell** [comment]
Regarding the new pushes, I notice you added *.back and not *.bak.  Add *.bak as well since I think it tends to be more common.  Other than that, once we reach consensus on point 3, LGTM👍

**Comment by JonhasSC** [comment]
> Regarding the new pushes, I notice you added *.back and not *.bak. Add *.bak as well since I think it tends to be more common. Other than that, once we reach consensus on point 3, LGTM👍

oops thats a typo, thanks!

**Comment by zmorrell** [comment]
LGTM

**Pull request merged**
