### PR TITLE
Patch to generate Clifford + T for InverseComposite subcircuit for qsp circuits

### PR DESCRIPTION
**Pull request by JonhasSC**
Small patch to respond to issue https://github.com/lanl-ansi/qc-applications/issues/24 This issue stems from cirq generating a series of gates when it encountered a CNOT**-1 gate. Given that, this patch introduces using `print_to_openqasm` from `pyLIQTR.utils.qsp_helpers`. Note that openqasm from pyLIQTR did not give the appropriate results but print_to_openqasm did 🤷

### CODE REVIEW

**Comment by zmorrell** [comment]
Is the modification for the notebook just the result of re-running it and ensuring that there have been no breaking changes?

**Comment by JonhasSC** [comment]
> Is the modification for the notebook just the result of re-running it and ensuring that there have been no breaking changes?

No, so from the circuit_estimate function, you will notice that rather than using QasmOutput from cirq, we are now using print_to_openqasm from pyliqtr. This function does not suffer from any of the issues that cirq does when encountering inverse gates, so it generates the appropriate qasm for a given subcirucit

**Comment by JonhasSC** [comment]
> Is the modification for the notebook just the result of re-running it and ensuring that there have been no breaking changes?

oops I read your comment wrong. Yes, the only changes to the notebook is passing in a write_circuits=True flag when generating resource estimates to assuring that we are generating the appropriate qasm

**Comment by JonhasSC** [comment]
Given our discussion, and how the output runtime error from numpy looks to originate from an environment/architecture issue (and how it does not affect the generated output), I will be merging this PR

**Pull request merged**
